django/dreamcatcher/dreamcatcher/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from dreams.views import CustomPasswordResetView

from dreams import views

urlpatterns = [
    # Admin URLs
    path('admin/', admin.site.urls),

    # Dreams URLs
    path('dreams/', include('dreams.urls')),

    # User Authentication URLs
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),

    # Custom URLs
    path('aboutus/', views.aboutus, name='aboutus'),
    path('', views.home, name='home'),

    # Password Reset URLs
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='registration/password_reset.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
        success_url='/password_reset/done/'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url='/reset/done/'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

]

django/dreamcatcher/dreams/urls.py
from django.urls import path
from .views import profile
from . import views

app_name = 'dreams'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('home_logged_in/', views.home_logged_in, name='home_logged_in'),
    path('log_dream/', views.log_dream, name='log_dream'),
    path('choose_title/<int:dream_id>/', views.choose_title, name='choose_title'),
    path('choose_title_log/<int:dream_id>/', views.choose_title_log, name='choose_title_log'),
    path('dreams/regenerate_titles/<int:dream_id>/', views.regenerate_titles, name='regenerate_titles'),
    path('choose_emotion/<int:dream_id>/', views.choose_emotion, name='choose_emotion'),
    path('questionnaire/<int:dream_id>/', views.questionnaire, name='questionnaire'),
    path('questionnaire_log/<int:dream_id>/', views.questionnaire_log, name='questionnaire_log'),
    path('journal/', views.dream_journal, name='dream_journal'),
    path('edit_dream/<int:dream_id>/', views.edit_dream, name='edit_dream'),
    path('add_to_favorites/<int:dream_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:dream_id>/', views.remove_from_favorites, name='remove_from_favorites'),
    path('share_dream/<int:dream_id>/', views.share_dream, name='share_dream'),
    path('share_dream_anon/<int:dream_id>/', views.share_dream_anon, name='share_dream_anon'),
    path('unshare_dream/<int:dream_id>/', views.unshare_dream, name='unshare_dream'),
    path('delete_dream/<int:dream_id>/', views.delete_dream, name='delete_dream'),
    path('like_dream/<int:dream_id>/', views.like_dream, name='like_dream'),
    path('unlike_dream/<int:dream_id>/', views.unlike_dream, name='unlike_dream'),
    path('view_similar_own/<int:dream_id>/', views.view_similar_own, name='view_similar_own'),
    path('view_similar_all/<int:dream_id>/', views.view_similar_all, name='view_similar_all'),
    path('view_favorite/', views.view_favorite, name='view_favorite'),
    path('view_shared/', views.view_shared, name='view_shared'),
    path('view_own_shared/', views.view_own_shared, name='view_own_shared'),
    path('users/<str:username>/', views.view_users_dreams, name='view_users_dreams'),
    path('view_liked', views.view_liked, name='view_liked'),
    path('add_comment/<int:dream_id>/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('statistics/', views.personal_statistics, name='personal_statistics'),
    path('gallery/', views.gallery, name='gallery')
]

django/dreamcatcher/templates/aboutus.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>About us </title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👯‍♀</text></svg>">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap');

        body, html {
            padding: 0;
            width: 100%;
            height: 100%;
            font-family: 'DM Sans', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            text-align: center;
            background: linear-gradient(to right, #e7c3f1, #cdb4eb, #b9c9ec, #e6eeff);
        }
    
        .image-container img {
            width: 100%; 
            max-width: 600px;
            border-radius: 0; 
        }
        .person-container {
            display: flex;
            justify-content: center;
            max-width: 800px; 
            margin: auto; 
        }
        .person {
            flex: 1;
            padding: 20px;
            background-color: rgba(127, 197, 243, 0.217);
            border: 2px solid #5a1a8b; 
            margin: 10px;
            text-align: center;
            border-radius: 0;
        }
        .person h2 {
            color: #5a1a8b; 
        }
        .person p {
            color: #2e0e47; 
            margin-top: 10px;
        }
        .together {
            font-size: 1.2rem;
            margin-top: 20px;
            color: #5a1a8b; 
        }
        .join-us {
            font-size: 1.2rem; 
            margin-top: 10px; 
            color: #5a1a8b;
        }
        .emojis {
            font-size: 2rem; 
            margin-top: 10px; 
        }
        h1 {
            color: #5a1a8b;
        }
        .overlay {
            display: flex;
            flex-direction: row;
            align-items: center;
            justify-content: center;
            margin-top: 20px;
        }
        .overlay button {
            padding: 15px 30px;
            font-size: 1.2vw;
            width: 150px;
            margin: 0 10px;
            border-radius: 25px;
            background-color: transparent; 
            color: #7851a9; 
            border: 2px solid #7851a9; 
            cursor: pointer;
            transition: background-color 0.3s, transform 0.3s;
            letter-spacing: 1px;
            transition: transform 0.5s ease;
            font-family: 'Manrope';
        }
        .overlay button:hover {
            background-color: #7851a9;
            border: 2px solid #7851a9; 
            color: white;
        }

        .join-us-container {
            width: 100%;
            background-color: transparent;
            margin-top: 30px;
            margin-bottom: 50px;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
        }

        #more-info {
            padding: 20px;
            justify-content: center;
            display: block;
            margin-left: auto;
            margin-right: auto;
            margin-top: 50px;
            border: 3px solid #5a1a8b;
            border-top: 0;
            border-bottom: 0;
            border-radius: 25px;
            color: #5a1a8b;
            box-sizing: border-box;
            width: 30%;
            font-family: 'DM Sans', sans-serif;
            font-size: 1.2vw;
            line-height: 1.5;
        }
    </style>
    </head>
    <body>
        <h1>👩🏻‍💻 Meet the creators! 👩🏼‍💻</h1>

        <div class="image-container">
            <img src="{% static 'images/creators.jpg' %}" alt="Creators of DreamCatcher">
        </div>
        
        <div class="person-container">
            <div class="person">
                <h2>Hannah Steinbach</h2>
                <p>Hallo! I am Hannah, and I am a princess. 👸🏻</p>
                <p>My DreamCatcher is filled with predictions for who the next German Chancellor will be and with fears about my mircrobangs not turning out right.</p>
            </div>
            
            <div class="person">
                <h2>Raluca Rilla</h2>
                <p>Ciao. I am Raluca, and I am a princess. 👸🏼</p>
                <p>When I dream, I mostly dream about things I shouldn't be doing in real life, so I'm keeping track of my dreams to never run out of bad ideas. </p>
            </div>
        </div>
        
        <p class="together">Together, we never cease to dream big... And when we can't dream any bigger, we never fail to dream wilder.</p>
        
        </div>
        <section id="more-info">
            <p class="join-us"><b>Join us</b> in documenting the hilarious, the scary, and the plain weird. </p>
            <p class="emojis"> 🍬🪼🪻🫐</p>
            <div class="overlay">
                <form method="post" action="{% url 'login' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit">Log in</button>
                </form>
                <form method="post" action="{% url 'signup' %}" style="display: inline;">
                    {% csrf_token %}
                    <button type="submit">Sign up</button>
                </form>
            </div>
        </section>
        <div style="height: 70px;"></div>
    </body>
</html>

django/dreamcatcher/templates/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}DreamCatcher🫧{% endblock %}</title>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🌌</text></svg>">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Tiny5:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;700&display=swap');

        body, html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            font-family: 'DM Sans', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            background: linear-gradient(to right, #e7c3f1, #cdb4eb, #b9c9ec, #e6eeff);
            background-size: 600% 600%;
            animation: gradientAnimation 9s ease infinite;
        }

        @keyframes gradientAnimation {
            0% { background-position: 0% 50%; }
            50% { background-position: 100% 50%; }
            100% { background-position: 0% 50%; }
        }
        
        .full-screen {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            height: 100vh;
            text-align: center;
            position: relative;
        }
        .brand {
            font-size: 12vw;
            line-height: 1;
            color: #5a1a8b;
            margin-bottom: 20px;
            font-family: 'Raleway', sans-serif;
        }
        .subtitle {
            font-size: 1.2vw;
            margin-top: 50px;
            color: #3d1e54;
            letter-spacing: 0.5px;
            transition: transform 0.5s ease;
            font-family: 'Raleway', sans-serif;
        }
        .emojis {
            font-size: 3.5vw;
            margin-top: 50px;
            letter-spacing: 2px;
            transition: transform 0.5s ease;
        }
        .overlay {
            display: flex;
            flex-direction: row;
            align-items: center;
            margin-top: 20px;
        }
        .overlay button {
            padding: 15px 30px;
            font-size: 1.2vw;
            width: 150px;
            margin: 0 10px;
            border-radius: 25px;
            background-color: transparent; 
            color: #7851a9; 
            border: 2px solid #7851a9; 
            cursor: pointer;
            transition: background-color 0.3s, transform 0.3s;
            letter-spacing: 1px;
            transition: transform 0.5s ease;
            font-family: 'Manrope', sans-serif;
        }
        .overlay button:hover {
            background-color: #7851a9;
            border: 2px solid #7851a9; 
            color: white;
            transform: scale(1.05);
        }
        #explore-dreams {
            margin-top: 10px;
        }
        #more-info {
            padding: 20px;
            margin-top: 50px;
            border: 3px solid #5a1a8b;
            border-top: 1px;
            border-bottom: 0;
            border-radius: 25px;
            color: #5a1a8b;
            box-sizing: border-box;
            width: 100%;
            font-family: 'Manrope', sans-serif;
            font-size: 1.2vw;
            line-height: 1.5;
        }

        .messages {
            margin: 10px 0;
            padding: 10px;
            border-radius: 5px;
            background-color: rgba(255, 255, 255, 0.7);
            color: #3d1e54;
            font-size: 26px;
            font-weight: normal;
        }
        .playlist-container {
            display: flex;
            justify-content: center;
            gap: 20px;
        }
        .playlist-container iframe {
            border-radius: 12px;
            width: 45%;
            height: 352px;
        }

        html {
            scroll-behavior: smooth;
        }

    </style>
</head>
<body>
    <div class="full-screen">
        <div class="brand">
            <div>Dream</div>
            <div>Catcher</div>
        </div>
        {% if messages %}
            <div class="messages" style="background-color: rgba(255, 255, 255, 0.3); color: #492c66; font-size: 15px; font-weight: normal;">
                {% for message in messages %}
                    <p>{{ message }}</p>
                {% endfor %}
            </div>
        {% endif %}
        <div class="overlay">
            <form method="post" action="{% url 'login' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit">Log in</button>
            </form>
            <form method="post" action="{% url 'signup' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit">Sign up</button>
            </form>
        </div>
        <div class="emojis">💫🫧🪁</div>
        <div id="explore-dreams" class="subtitle">explore your dreams</div>
    </div>
    <main>
        {% block content %}
        {% endblock %}
        <section id="more-info">
            <h2>More about the DreamCatcher</h2>
            <p>The DreamCatcher is a digital dream journal powered by a Large Language Model. You can use it to digitally store and access your dreams.</p>
        </section>
        <section id="more-info">
            <h2>Dreamy Tunes</h2>
            <p>In case you're curious about what <a class="btn btn-primary" href="{% url 'aboutus' %}">we</a> listen to while working on the DreamCatcher...</p>
            <div class="playlist-container">
                <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/3qcG06thoT5dON4ZBigN8N?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
                <iframe allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write" frameborder="0" height="450" style="width:100%;max-width:660px;overflow:hidden;border-radius:10px;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/ro/playlist/dreamcatching/pl.u-BNA6rMJF1NLNW5V"></iframe>
            </div>
        </section>
    </main>
    <footer>
        <p>&copy; 2024 DreamCatcher | Raluca Rilla & Hannah Steinbach | <a class="btn btn-primary" href="{% url 'aboutus' %}">About us</a></p>
    </footer>
    <script>
        window.addEventListener('scroll', function() {
            var subtitle = document.querySelector('.subtitle');
            var emojis = document.querySelector('.emojis');
            var buttons = document.querySelectorAll('.overlay button');
            var scrolled = window.pageYOffset || document.documentElement.scrollTop;
            var maxScroll = 80;
            var scrollFactor = Math.min(scrolled * 0.3, maxScroll);

            subtitle.style.transform = 'translateY(' + scrollFactor + 'px)';
            emojis.style.transform = 'translateY(' + scrollFactor + 'px)';
            buttons.forEach(function(button) {
                button.style.transform = 'translateY(' + scrollFactor + 'px)';
            });
        });
    </script>
</body>
</html>

django/dreamcatcher/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🏠</text></svg>">
    <title>DreamCatcher</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Raleway:wght@300;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;700&display=swap');
        
        body, html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            font-family: 'Manrope', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            background: linear-gradient(to right, #e7c3f1, #cdb4eb, #b9c9ec, #e6eeff);
        }
        .header {
            text-align: center;
            padding: 20px;
            background-color: rgba(248, 249, 250, 0.8);
            position: relative;
        }
        .profile{
            position: absolute;
            top: 0px;
            left: 20px;
            margin-left: 100px;
            font-size: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 3vw;
            color: #5a1a8b;
            font-family: 'Raleway', sans-serif;
            font-weight: normal;
            letter-spacing: 1px;
        }
        .logout-button {
            position: absolute;
            top: 0px;
            right: 20px;
            padding: 20px 40px;
            font-size: 30px;
        }
        .container {
            text-align: center;
            padding: 20px;
        }
        .dashboard {
            background: rgba(255, 255, 255, 0.8);
            padding: 20px;
            border-radius: 15px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            max-width: 1200px;
            margin-left: auto;
            margin-right: auto;
        }
        .dashboard h2 {
            color: rgba(103, 96, 240);
            font-size: 2.5vw;
            margin-bottom: 20px;
        }
        .stats {
            display: flex;
            justify-content: space-around;
            flex-wrap: wrap;
        }

        .stat {
            width: 200px;  
            height: 100px; 
            background: rgba(103, 96, 240, 0.1);
            border-radius: 10px;
            padding: 10px;
            margin: 10px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        .stat h3 {
            color: rgba(103, 96, 240);
            font-size: 1.5vw;
        }
        .stat p {
            color: #3D3D3D;
            font-size: 1.2vw;
            margin-top: 1px;
        }
        .stat_streak {
            width: 200px;
            height: 100px;
            background: rgba(103, 96, 240, 0.1);
            border-radius: 10px;
            padding: 10px;
            margin: 10px;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            justify-content: center;
        }

        .stat_streak h3 {
            color: rgba(103, 96, 240);
            font-size: 1.5vw;
            margin-bottom: 5px;
        }

        .stat_streak p {
            color: #3D3D3D;
            font-size: 1.2vw;
            margin: 2px 0;
        }

        .stat_streak .max-streak {
            font-size: 1vw;
            color: #3D3D3D;
            margin-top: 5px;
        }

        #word-cloud {
            margin-top: 20px;
        }
        #word-cloud-content {
            width: 100%;
            height: 300px;
            margin-top: 20px;
        }
        .menu ul {
            padding: 0;
            margin: 0;
            list-style: none;
        }
        .menu li {
            margin: 10px;
        }
         .button {
            padding: 10px;
            border: none;
            border-radius: 5px;
            background-color: rgba(103, 96, 240, 0.736);
            font-size: 22px;
            cursor: pointer;
            text-decoration: none;
            transition: background-color 0.3s;
            font-family: 'Manrope';
            letter-spacing: inherit;
            color: white;
            width: 300px;
            height: 100px;
            display: inline-flex;
            align-items: center;
            justify-content: center;
        }

        .button:hover {
            background-color: rgba(103, 96, 240);
            text-decoration: none;
            width: 300px;
            font-size: 22px;
            height: 100px;
            color: white;
        }

        .grid-menu {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            justify-items: center;
        }
        .tutorial {
            display: none;
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: rgba(0, 0, 0, 0.5);
            align-items: center;
            justify-content: center;
        }
        .tutorial .step {
            background: white;
            padding: 20px;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            text-align: center;
            width: 20%;
            margin: auto;
        }
        .tutorial .next-step, .tutorial .finish-tutorial {
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            background-color: rgba(103, 96, 240, 0.7);
            color: white;
            font-size: 1.2vw;
            cursor: pointer;
            height: auto;
            transition: background-color 0.3s;
        }
        .tutorial .next-step:hover, .tutorial .finish-tutorial:hover {
            background-color: rgba(103, 96, 240);
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>DreamCatcher</h1>
        <div class="profile">
            <a href="{% url 'dreams:profile' %}">
                <img src="{% static 'pfps/'|add:user.profile.avatar %}"
                     style="width: 80px; height: 80px; border-radius: 50%; border: 5px solid #cdb4eb; box-shadow: 0 0 10px #cdb4eb;">
            </a>
        </div>
        <div class="logout-button">
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit">Log out</button>
                </form>
            {% endif %}
        </div>
    </div>
    <div class="container">
        <div class="dashboard">
            <h2>Welcome, {{ user.username }}!</h2>
            <p>Let's take a journey into your subconscious! 🗺️</p>
            <div class="stats">
                <div class="stat">
                    <h3><a href="{% url 'dreams:dream_journal'%}" style="text-decoration: none; color: inherit;">Dreams logged</a></h3>
                    <p>{{ dream_count }}</p>
                </div>
                <div class="stat">
                    <h3><a href="{% url 'dreams:view_liked' %}" style="text-decoration: none; color: inherit;"  >Dreams liked</a></h3>
                    <p>{{ liked_count }}</p>
                </div>
                <div class="stat">
                    <h3><a href="{% url 'dreams:view_own_shared' %}" style="text-decoration: none; color: inherit;">Dreams shared</a></h3>
                    <p>{{ shared_count }}</p>
                </div>
                <div class="stat_streak">
                    <h3>Dream Streak</h3>
                    {% if dream_streak == 1 %}
                        <p>{{ dream_streak }} day</p>
                    {% else %}
                        <p>{{ dream_streak }} days</p>
                    {% endif %}
                    <p class="max-streak" style="font-size: 8pt; color: rgba(103, 96, 240)"><b>Longest streak:</b>
                    {% if max_streak == 1 %}
                        {{ max_streak }} day
                    {% else %}
                        {{ max_streak }} days</p>
                    {% endif %}
                </div>
            </div>
        </div>
        <nav class="menu">
            <ul class="grid-menu">
                <li><a href="{{ log_dream_url }}" class="button">Log a new dream 📝</a></li>
                <li><a href="{{ dream_journal_url }}" class="button">Dream Journal 📓</a></li>
                <li><a href="{{ gallery_url }}" class="button">Dream Gallery 🎨</a></li>
                <li><a href="{{ personal_statistics_url }}" class="button">Personal Statistics 🔎</a></li>
            </ul>
        </nav>
        <div id="word-cloud">
            <div id="word-cloud-content"></div>
        </div>
        <footer>
            <p>&copy; 2024 DreamCatcher | Raluca Rilla & Hannah Steinbach | <a class="btn btn-primary" href="{% url 'aboutus' %}">About us</a></p>
        </footer>
    </div>
    
    <div id="tutorial" class="tutorial">
        <div class="step" data-step="0">
            <p>Welcome to the best place to catch your dreams. Let's start with a short walkthrough! 🧸</p>
            <button class="next-step">Next</button>
        </div>
        <div class="step" data-step="1" data-target="log_dream">
            <p class="tutemoji" style="font-size: 19pt;">📝</p>
            <p>Click on <b>Log a new dream</b> and you can jot down your most recent dreams, and then patiently wait for the LLM to do its magic. 🪄</p>
            <button class="next-step">Next</button>
        </div>
        <div class="step" data-step="2" data-target="dream_journal">
            <p class="tutemoji" style="font-size: 19pt;">📓</p>
            <p>In your <b>Dream Journal</b>, you can see all of the dreams we've caught for you. You can search dreams by keywords, emotions, characters, and places.</p>
            <button class="next-step">Next</button>
        </div>
        <div class="step" data-step="3" data-target="gallery">
            <p class="tutemoji" style="font-size: 19pt;">🎨</p>
            <p>If you want to read about what others have been dreaming about, take a stroll through the <b>Dream Gallery</b>. You can like dreams, leave comments, and share your own dreams (anonymously if that's your thing...)</p>
            <button class="next-step">Next</button>
        </div>
        <div class="step" data-step="4" data-target="personal_statistics">
            <p class="tutemoji" style="font-size: 19pt;">🔎</p>
            <p>Finally, <b>Personal Statistics</b> has some insights about all of your dreams.</p>
            <button class="finish-tutorial">Start DreamCatching!</button>
        </div>
    </div>
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/d3-cloud@1.2.5/build/d3.layout.cloud.min.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const showTutorial = {{ show_tutorial|yesno:"true,false" }};
            if (showTutorial) {
                const tutorial = document.querySelector('.tutorial');
                const steps = tutorial.querySelectorAll('.step');
                let currentStep = 0;

                function showStep(stepIndex) {
                    steps.forEach((step, index) => {
                        step.style.display = index === stepIndex ? 'block' : 'none';
                    });
                }

                function nextStep() {
                    currentStep++;
                    if (currentStep < steps.length) {
                        showStep(currentStep);
                    } else {
                        tutorial.style.display = 'none';
                        sessionStorage.setItem('tutorialDisplayed', 'true');
                    }
                }

                tutorial.style.display = 'flex';
                showStep(currentStep);

                tutorial.querySelectorAll('.next-step, .finish-tutorial').forEach(button => {
                    button.addEventListener('click', nextStep);
                });
            }

            var words = {{ word_cloud_data|safe }};

            var layout = d3.layout.cloud()
                .size([500, 300])
                .words(words.map(function(d) {
                    return {text: d.text, size: d.size};
                }))
                .padding(5)
                .fontSize(function(d) { return d.size; })
                .on("end", draw);

            layout.start();

            function draw(words) {
                d3.select("#word-cloud-content").append("svg")
                    .attr("width", layout.size()[0])
                    .attr("height", layout.size()[1])
                    .append("g")
                    .attr("transform", "translate(" + layout.size()[0] / 2 + "," + layout.size()[1] / 2 + ")")
                    .selectAll("text")
                    .data(words)
                    .enter().append("text")
                    .style("font-size", function(d) { return d.size + "px"; })
                    .style("fill", "#6760f0")
                    .attr("text-anchor", "middle")
                    .attr("transform", function(d) {
                        return "translate(" + [d.x, d.y] + ")rotate(" + d.rotate + ")";
                    })
                    .text(function(d) { return d.text; });
            }
        });
    </script>
</body>
</html>