django/dreamcatcher/dreamcatcher/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from dreams.views import CustomPasswordResetView

from dreams import views

urlpatterns = [
    # Admin URLs
    path('admin/', admin.site.urls),

    # Dreams URLs
    path('dreams/', include('dreams.urls')),

    # User Authentication URLs
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/logout/', views.logout_view, name='logout'),
    path('signup/', views.signup, name='signup'),

    # Custom URLs
    path('aboutus/', views.aboutus, name='aboutus'),
    path('', views.home, name='home'),

    # Password Reset URLs
    path('password_reset/', CustomPasswordResetView.as_view(
        template_name='registration/password_reset.html',
        email_template_name='registration/password_reset_email.html',
        subject_template_name='registration/password_reset_subject.txt',
        success_url='/password_reset/done/'
    ), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='registration/password_reset_done.html'
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='registration/password_reset_confirm.html',
        success_url='/reset/done/'
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='registration/password_reset_complete.html'
    ), name='password_reset_complete'),

]

django/dreamcatcher/dreams/urls.py
from django.urls import path
from .views import profile
from . import views

app_name = 'dreams'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('home_logged_in/', views.home_logged_in, name='home_logged_in'),
    path('log_dream/', views.log_dream, name='log_dream'),
    path('choose_title/<int:dream_id>/', views.choose_title, name='choose_title'),
    path('choose_title_log/<int:dream_id>/', views.choose_title_log, name='choose_title_log'),
    path('dreams/regenerate_titles/<int:dream_id>/', views.regenerate_titles, name='regenerate_titles'),
    path('choose_emotion/<int:dream_id>/', views.choose_emotion, name='choose_emotion'),
    path('questionnaire/<int:dream_id>/', views.questionnaire, name='questionnaire'),
    path('questionnaire_log/<int:dream_id>/', views.questionnaire_log, name='questionnaire_log'),
    path('journal/', views.dream_journal, name='dream_journal'),
    path('edit_dream/<int:dream_id>/', views.edit_dream, name='edit_dream'),
    path('add_to_favorites/<int:dream_id>/', views.add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:dream_id>/', views.remove_from_favorites, name='remove_from_favorites'),
    path('share_dream/<int:dream_id>/', views.share_dream, name='share_dream'),
    path('share_dream_anon/<int:dream_id>/', views.share_dream_anon, name='share_dream_anon'),
    path('unshare_dream/<int:dream_id>/', views.unshare_dream, name='unshare_dream'),
    path('delete_dream/<int:dream_id>/', views.delete_dream, name='delete_dream'),
    path('like_dream/<int:dream_id>/', views.like_dream, name='like_dream'),
    path('unlike_dream/<int:dream_id>/', views.unlike_dream, name='unlike_dream'),
    path('view_similar_own/<int:dream_id>/', views.view_similar_own, name='view_similar_own'),
    path('view_similar_all/<int:dream_id>/', views.view_similar_all, name='view_similar_all'),
    path('view_favorite/', views.view_favorite, name='view_favorite'),
    path('view_shared/', views.view_shared, name='view_shared'),
    path('view_own_shared/', views.view_own_shared, name='view_own_shared'),
    path('users/<str:username>/', views.view_users_dreams, name='view_users_dreams'),
    path('view_liked', views.view_liked, name='view_liked'),
    path('add_comment/<int:dream_id>/', views.add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('statistics/', views.personal_statistics, name='personal_statistics'),
    path('gallery/', views.gallery, name='gallery')
]

django/dreamcatcher/dreams/models.py
import re
from collections import Counter
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from django.utils import timezone
from django.db.models.signals import post_save
from datetime import timedelta
from django.db import transaction # avoid partial commits
from django.dispatch import receiver
from datetime import datetime
from langchain_community.llms import ollama
import json



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    avatar = models.CharField(max_length=100, choices=[
        ('1.jpg', 'Picture 1'),
        ('3.jpg', 'Picture 3'),
        ('4.jpg', 'Picture 4'),
        ('5.jpg', 'Picture 5'),
        ('6.jpg', 'Picture 6'),
        ('7.jpg', 'Picture 7'),
        ('8.jpg', 'Picture 8'),
        ('9.jpg', 'Picture 9'),
        ('10.jpg', 'Picture 10'),
        ('11.jpg', 'Picture 11'),
        ('12.jpg', 'Picture 12'),
        ('13.jpg', 'Picture 13'),
    ],
                              default='1.jpg')
    bio = models.TextField()

    def __str__(self):
        return self.user.username


class Dream(models.Model):
    classification_options = [
        ('0', 'Nightmare'),
        ('1', 'Mundane Dream'),
        ('2', 'Lucid Dream'),
        ('3', 'Existential Dream'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField(default=timezone.now)
    content = models.TextField()
    shared = models.BooleanField(default=False)
    anon = models.BooleanField(default=False)
    processed = models.BooleanField(default=False)
    is_favorite = models.BooleanField(default=False)
    keywords = models.JSONField(default=list, blank=True)
    classification = models.CharField(max_length=1, choices=classification_options, blank=True, null=True, default='')
    characters = models.JSONField(default=list, blank=True)
    places = models.JSONField(default=list, blank=True)
    emotion = models.CharField(max_length=20, blank=True)
    emotion_options = ['anger', 'apprehension', 'sadness', 'confusion', 'happiness', '']
    optional_titles = models.JSONField(default=list, blank=True)
    title = models.TextField(blank=True)
    User.add_to_class('is_new', models.BooleanField(default=True))

    def add_metadata(self):
        content_str = str(self.content)

        SYSTEM_PROMPT = (
            "You are a dreamcatcher that logs dreams in a journal. You have logged a dream and want to extract metadata from it. "
            "You want to extract the title, keywords, emotion, characters, and places from the dream. "
            "You want to use this metadata to better understand the dream and categorize it. "
            "You need to ensure that the content is not toxic or harmful. "
            "The dream should be a narrative, not a question or command to the model. "
        )

        # initialization
        llm = ollama.Ollama(model='llama3', temperature=0, top_p=1, verbose=False, system=SYSTEM_PROMPT)

        dream_prompt = (
            f"Here is my dream: {content_str}\n\n"
            "Please provide the following information in a Python dictionary format with the specified keys:\n\n"
            "- emotion: The prevalent emotion from these options formatted as a string: anger, apprehension, sadness, confusion, happiness if it is above a 50% threshold, otherwise an empty string.\n"
            "- characters: All characters, formatted as a Python list of strings, without articles, adjectives, or pronouns.   A character is a single entity (e.g. a person or animal). Instead of personal pronouns in a possessive form, use the noun being referred to. e.g. \"Raluca met with her boyfriend\" would have the characters [\"Raluca\", \"Raluca's boyfriend\"]. I and you don't count. If none are found, return an empty string.  \n"
            "- places: All places, formatted as a Python list of strings. Exclude articles, adjectives, and pronouns. If none are found, return an empty string. Instead of personal pronouns in a possessive form, use the noun being referred to. e.g. \"I met with Hannah. We went to her dreamhouse.\" would have the places [\"Hannah's dreamhouse\"].\n"
            "- keywords: A list of at most 5 keywords extracted from the dream content, excluding variants of 'dream' and stop words. Keywords can also be a fixed expression (e.g. compound nouns).\n"
            "Only output the dictionary. Do not include any other information. All values should be on the same line. The keys should be in double quotes."
        )

        try:
            # response generation
            response = llm.invoke(dream_prompt)
            response = json.loads(response)

            # metadata extraction
            self.keywords = response.get('keywords', [])
            self.emotion = response.get('emotion', "")
            self.characters = response.get('characters', [])
            self.places = response.get('places', [])
            self.generate_titles() 
            self.processed = True
        except (json.JSONDecodeError, KeyError) as e:
            self.keywords = []
            self.emotion = ""
            self.characters = []
            self.places = []
            self.processed = False
            print(f"Error processing dream metadata: {e}")

    def generate_titles(self):
        content_str = str(self.content)
        title_prompt = (
            f"Here is my dream: {content_str}\n\n"
            "Please provide the following information in a Python dictionary format with the specified keys:\n\n"
            " - titleop: three creative title options, formatted as a Python list of strings.\n"
            "Only output the dictionary. Do not include any other information. All values should be on the same line. The keys should be in double quotes."
        )
        llm = ollama.Ollama(model='llama3', temperature=1, top_p=1, verbose=False)
        try:
            response = llm.invoke(title_prompt)
            response = json.loads(response)
            self.optional_titles = response.get('titleop', [])
        except Exception as e:
            self.optional_titles = []
            print(f"Error generating titles: {e}")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.add_metadata()
        super().save(*args, **kwargs)


    def likes_count(self):
        return self.likes.count()

    def liked_users(self):
        return [like.user for like in self.likes.all()]

    def classification_string(self):
        return dict(self.classification_options).get(self.classification, "No classification")

    def __str__(self):
        return f"{self.date}: {self.content[:50]}"


class DreamLike(models.Model):
    dream = models.ForeignKey(Dream, on_delete=models.CASCADE, related_name='likes')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    liked_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('dream', 'user')

    def __str__(self):
        return f"{self.user.username} likes {self.dream}"


class Questionnaire(models.Model):
    dream = models.OneToOneField(Dream, on_delete=models.CASCADE, related_name='questionnaire')
    quality_option = [
        ('0', 'Very poor'),
        ('1', 'Poor'),
        ('2', 'Neutral'),
        ('3', 'Good'),
        ('4', 'Very Good'),
    ]

    boolean_option = [
        ('0', 'No'),
        ('1', 'Yes'),
    ]

    duration_option = [
        ('0', 'Less than 3 hours'),
        ('1', '3-5 hours'),
        ('2', '6-8 hours'),
        ('3', 'More than 8 hours'),
    ]

    stress = models.CharField(max_length=1, choices=boolean_option, blank=True, null=True)
    creativity = models.CharField(max_length=1, choices=boolean_option, blank=True, null=True)
    sleep_duration = models.CharField(max_length=1, choices=duration_option, blank=True, null=True)
    sleep_quality = models.CharField(max_length=1, choices=quality_option, blank=True, null=True)
    awakening = models.CharField(max_length=1, choices=boolean_option, blank=True, null=True)
    morning_mood = models.CharField(max_length=1, choices=boolean_option, blank=True, null=True)
    dream_relation_oneself = models.CharField(max_length=1, choices=boolean_option, blank=True, null=True)
    dream_impact_mood = models.CharField(max_length=1, choices=boolean_option, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"Questionnaire for {self.dream.title}"


class Comment(models.Model):
    dream = models.ForeignKey(Dream, related_name='comments', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.author.username} - {self.text}'

    def can_delete(self, user):
        return user == self.author


class MonthlyRecap(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    month = models.DateField()

    # Dream-related fields
    dream_count = models.PositiveIntegerField(default=0)
    top_keywords = models.JSONField(default=list, blank=True)  # top 3
    top_classification = models.JSONField(default=list, blank=True)
    top_characters = models.JSONField(default=list, blank=True)  # top 3
    top_places = models.JSONField(default=list, blank=True)  # top 3
    top_emotion = models.CharField(max_length=20, blank=True)

    # Questionnaire-related fields
    avg_stress = models.FloatField(null=True, blank=True)
    most_common_sleep_duration = models.JSONField(default=dict, blank=True)
    most_common_sleep_quality = models.JSONField(default=dict)
    avg_awakening = models.FloatField(null=True, blank=True)
    avg_creativity = models.FloatField(null=True, blank=True)
    avg_morning_mood = models.FloatField(null=True, blank=True)
    avg_dream_relation_oneself = models.FloatField(null=True, blank=True)

django/dreamcatcher/dreams/templates/dreams/add_comments.html
<!-- add_comment.html -->
{% extends 'base_generic.html' %}

{% block content %}
  <h1>Add Comment to {{ dream.title }}</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Post Comment</button>
  </form>
{% endblock %}

django/dreamcatcher/dreams/templates/dreams/choose_title.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🖋️</text></svg>">
    <title>{% block title %}Log a Dream{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;700&display=swap');
        body, html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            font-family: 'Manrope', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
        }
        .sidenav {
            height: 100%;
            width: 180px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: rgba(103, 96, 240, 0.224);
            overflow-x: hidden;
            padding-top: 50px;
        }
        .sidenav a {
            padding: 6px 8px 6px 18px;
            text-decoration: none;
            font-size: 16px;
            color: #3D3D3D;
            display: block;
            border-bottom: 1px solid #ddd;
        }
        .sidenav a:last-child {
            border-bottom: none;
        }
        .sidenav a:hover {
            color: black;
        }
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            width: calc(100% - 200px);
            margin-left: 200px;
            margin-top: 30px;
            z-index: 1;
            max-width: 1200px;
            margin-left: 180px;
            margin: 0 auto;
        }
        .container h2 {
            margin-top: 0;
        }
        .header {
            background: #FFFFFF;
            color: #3D3D3D;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 40%;
            text-align: center;
            margin-top: 20px;
            margin-left: 180px;
            margin-bottom: 80px;
            z-index: 2;
            position: relative;
        }
        .centered-text {
            text-align: center;
            margin-left: 200px;
            font-family: 'Manrope', 'sans-serif';
        }
        .title-options {
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        #loading-icon {
            width: 40px; 
            height: 40px; 
            margin-right: 10px;
        }
        #loading-content {
            display: flex;
            align-items: center;
            justify-content: center; 
        }
        #loading-container {
            display: none;
            text-align: center;
            margin-bottom: 20px;
        }
        #loading-message {
            font-size: 16px;
            margin: 0;
        }

        .btn-title {
            padding: 10px 20px;
            background-color: rgba(103, 96, 240);
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        } */

        /* .btn:hover {
            background-color: #4e47d1;
        } */
    </style>
</head>
<body>
    <div class="sidenav">
        <a href="{% url 'dreams:profile' %}" class="profile-link">
            <img src="{% static 'pfps/'|add:user.profile.avatar %}"
                 style="width: 100px; height: 100px; border-radius: 50%; border: 5px solid #cdb4eb; box-shadow: 0 0 10px #808080;">
            <br></br>
            <span>My Profile</span>
        </a>
        <a href="/">Home</a>
        <a href="{% url 'dreams:gallery' %}">Dream Gallery</a>
        <a href="{% url 'dreams:log_dream' %}"><b>Log a dream</b></a>
        <a href="{% url 'dreams:dream_journal' %}">Dream Journal</a>
        <a href="{% url 'dreams:personal_statistics' %}">Personal Statistics</a>
        <a href="{% url 'logout' %}">Log out</a>
    </div>
    <div class="header">
        <h2>Dream titles 📰</h2>
    </div>
    <section class="content">
        <div class="centered-text">
            <div id="loading-container">
                <div id="loading-content">
                    <img id="loading-icon" src="{% static 'images/loading.gif' %}" alt="Loading...">
                    <p id="loading-message">Generating other title options... 💫</p>
                </div>
            </div>

            {% if dream.optional_titles %}
                <p>Choose a title to display in your dream journal from the following options:</p>
                <div class="title-options">
                    {% for title in dream.optional_titles %}
                        <form class="keyword-form" method="post" action="{% url 'dreams:choose_title' dream.id %}">
                            {% csrf_token %}
                            <br>
                            <button type="submit" class="btn-title" name="title" style="height: auto;" value="{{ title }}">{{ title }}</button>
                            <br>
                        </form>
                    {% endfor %}
                </div>
                <br>
                {% if dream.id %}
                    <button class="btn" id="regenerate-btn" onclick="regenerateTitles()">Regenerate Titles</button>
                {% else %}
                    <p>Error: Dream ID is missing or invalid. Please try again later.</p>
                {% endif %}
            {% else %}
                <p>No optional titles available. Are you sure you logged a dream?</p>
                <a type="submit" class="btn" href="{% url 'dreams:log_dream' %}">Log a dream</a>
            {% endif %}
        </div>
    </section>

    <script>
        function regenerateTitles() {
            const loadingContainer = document.getElementById('loading-container');
            loadingContainer.style.display = 'block';

            const dreamId = "{{ dream.id }}";
            if (dreamId) {
                setTimeout(function() {
                    window.location.href = "{% url 'dreams:regenerate_titles' dream.id %}";
                }, 500);
            } else {
                console.error('Dream ID is missing or invalid.');
                loadingContainer.style.display = 'none';
                alert('Error: Dream ID is missing or invalid.');
            }
        }
    </script>

    <footer>
        <p>&copy; 2024 DreamCatcher | Raluca Rilla & Hannah Steinbach | <a class="btn btn-primary" href="{% url 'aboutus' %}">About us</a></p>
    </footer>
</body>
</html>

django/dreamcatcher/dreams/templates/dreams/log_dream.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🖋️</text></svg>">
    <title>{% block title %}Log a Dream{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">


    <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@300;700&display=swap');
        body, html {
            margin: 0;
            padding: 0;
            width: 100%;
            height: 100%;
            font-family: 'Manrope', -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
        }
        .sidenav {
            height: 100%;
            width: 180px;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: rgba(103, 96, 240, 0.224);
            overflow-x: hidden;
            padding-top: 50px;
        }
        .sidenav a {
            padding: 6px 8px 6px 18px;
            text-decoration: none;
            font-size: 16px;
            color: #3D3D3D;
            display: block;
            border-bottom: 1px solid #ddd;
        }
        .sidenav a:last-child {
            border-bottom: none;
        }
        .sidenav a:hover {
            color: black;
        }
        .container {
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: flex-start;
            width: calc(100% - 200px);
            margin-left: 200px;
            margin-top: 30px;
            z-index: 1;
            max-width: 1200px;
            margin-left: 180px;
            margin: 0 auto;
        }
        .container h2 {
            margin-top: 0;
        }
        .header {
            background: #FFFFFF;
            color: #3D3D3D;
            border-radius: 10px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            width: 40%;
            text-align: center;
            margin-top: 20px;
            margin-left: 180px;
            margin-bottom: 60px;
            z-index: 2;
            position: relative;
        }
        .chat-form {
            text-align: center;
            width: 80%;
            margin-left: 200px;
            max-width: 600px;
            margin-bottom: 20px;
            gap: 10px;
        }
        .chat-form textarea {
            width: 100%;
            padding: 10px;
            font-size: 18px;
            height: 200px;
            resize: vertical;
            border: 1px solid #ffffff;
            border-radius: 10px;
            margin-bottom: 8px;
            background-color: #ffffff;
            font-family: 'Manrope', sans-serif;
        }
        .chat-form input[type="submit"] {
            padding: 10px 24px;
            border: none;
            border-radius: 4px;
            background-color: rgb(104 96 240);
            color: white;
            font-size: 14px;
            cursor: pointer;
            transition: background-color 0.3s;
            height: 46px;
            line-height: normal;
            font-family: 'Manrope', sans-serif;
        }
        .chat-form input[type="submit"]:hover {
            background-color: rgba(103, 96, 240, 0.659);
        }
        #classification {
            padding: 10px;
            font-size: 14px;
            border: 1px solid #ffffff;
            border-radius: 4px;
            background-color: #ffffff;
            cursor: pointer;
            font-family: 'Manrope', sans-serif;
            height: 46px;
        }
        #classification option {
            padding: 8px;
            font-size: 14px;
            background-color: #f0f0f0;
            color: #1e3047;
        }

        #id_date {
            width: 35%;
            padding: 10px;
            margin-right: 5px;
            font-size: 14px;
            border: 1px solid #ffffff;
            border-radius: 4px;
            background-color: #ffffff;
            cursor: pointer;
            margin-bottom: 10px;
            box-sizing: border-box;
            font-family: 'Manrope', sans-serif;
        }
        #id_time{
            width: 35%;
            padding: 10px;
            font-size: 14px;
            border: 1px solid #ffffff;
            border-radius: 4px;
            background-color: #ffffff;
            cursor: pointer;
            margin-bottom: 10px;
            box-sizing: border-box;
            font-family: 'Manrope', sans-serif;
        }

        .playlist-container {
            display: flex;
            justify-content: center;
            gap: 20px;
            margin-left: 200px;
        }
        .playlist-container iframe {
            border-radius: 12px;
            width: 45%;
            height: 352px;
        }

        html {
            scroll-behavior: smooth;
        }

        .show-playlists .playlist-container {
            display: flex;
        }

        .centered-text {
            text-align: center;
            margin-left: 200px;
        }
        #loading-icon {
        width: 40px; 
        height: 40px; 
        margin-right: 10px;
        }
        #loading-content {
        display: flex;
        align-items: center;
        justify-content: center; 
        }
        #loading-container {
            display: none;
            text-align: center;
        }
        #loading-message {
        font-size: 16px;
        margin: 0;
        }

        #loading-info {
            font-size: 16px; 
            margin: 0;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <div class="sidenav">
        <a href="{% url 'dreams:profile' %}" class="profile-link">
            <img src="{% static 'pfps/'|add:user.profile.avatar %}"
                 style="width: 100px; height: 100px; border-radius: 50%; border: 5px solid #cdb4eb; box-shadow: 0 0 10px #808080;">
            <br></br>
            <span>My Profile</span>
        </a>
        <a href="/">Home</a>
        <a href="{% url 'dreams:gallery' %}">Dream Gallery</a>
        <a href="{% url 'dreams:log_dream' %}"><b>Log a dream</b></a>
        <a href="{% url 'dreams:dream_journal' %}">Dream Journal</a>
        <a href="{% url 'dreams:personal_statistics' %}">Personal Statistics</a>
        <a href="{% url 'logout' %}">Log out</a>
    </div>
    <div class="header">
        <h2>Log a Dream🖋️</h2>
    </div>
    <form class="chat-form" method="post" onsubmit="return handleSubmit()">
        {% csrf_token %}
        <input type="date" id="id_date" name="date">
        <textarea id="content" name="content" placeholder="What have you been dreaming about lately?" rows="4"></textarea>
        <select id="classification" name="classification">
            <option value="">Classify your dream</option>
            <option value="0">Nightmare</option>
            <option value="1">Mundane dream (very close to reality)</option>
            <option value="2">Lucid dream</option>
            <option value="3">Existential dream (intense bodily awareness)</option>
        </select>
        <input type="submit" value="Enter">
    </form>
    <section class="content">
            {% if messages %}
        <div class="alert alert-success">
            <ul>
                {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
        <div class="centered-text">
            <div id="loading-container" style="display: none; text-align: center;">
                <div id="loading-content">
                    <img id="loading-icon" src="{% static 'images/loading.gif' %}" alt="Loading...">
                    <p id="loading-message">Currently logging your dream 💌</p>
                </div>
                <p id="loading-info">Make the wait fly by with our dreamy tunes...</p>
            </div>
            <p id="default-message">Some dreamy tunes to get you in the right headspace 💭</p>
        </div>
        <div class="playlist-container">
            <iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/3qcG06thoT5dON4ZBigN8N?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>
            <iframe allow="autoplay *; encrypted-media *; fullscreen *; clipboard-write" frameborder="0" height="450" style="width:100%;max-width:660px;overflow:hidden;border-radius:10px;" sandbox="allow-forms allow-popups allow-same-origin allow-scripts allow-storage-access-by-user-activation allow-top-navigation-by-user-activation" src="https://embed.music.apple.com/ro/playlist/dreamcatching/pl.u-BNA6rMJF1NLNW5V"></iframe>
        </div>
    </section>
    <footer>
        <p>&copy; 2024 DreamCatcher | Raluca Rilla & Hannah Steinbach | <a class="btn btn-primary" href="{% url 'aboutus' %}">About us</a></p>
    </footer>
    <script>
        function handleSubmit() {
        const defaultMessage = document.getElementById('default-message');
        const loadingContainer = document.getElementById('loading-container');
        const submitButton = document.getElementById('submit-button');

        defaultMessage.style.display = 'none';
        loadingContainer.style.display = 'block';
        submitButton.disabled = true;
        submitButton.style.backgroundColor = 'rgba(103, 96, 240, 0.659)';

        return true;
        }
    </script>

</body>
</html>